version: '3.8'
services:
  backend:
    ports:
      - "4000:4000"
    build:
      context: ./backend
    container_name: backend
  frontend:
    ports:
      - "80:80"
    build:
      context: ./frontend
    container_name: frontend