version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - app-network
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge