version: '3.8'
services:
  backend:
    ports:
      - "${BACKEND_PORT}:5000"
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    container_name: backend
  frontend:
    ports:
      - "80:80"
    build:
      args:
        - REACT_APP_BACKEND_API_URL=/
      context: ./frontend
    container_name: frontend