version: '3.8'
services:
  backend:
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    container_name: backend
    networks:
      - app-network
  frontend:
    ports:
      - "80:80"
    build:
      args:
        - REACT_APP_BACKEND_API_URL=/
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge